name: testsuite

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:

jobs:

  ubuntu:
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: perl -V
        run: perl -V
      - name: Makefile.PL
        run: perl -I$(pwd) Makefile.PL
      - name: make test
        run: make test
      - name: prove xt
        run: prove -b xt

  linux:
    name: "linux ${{ matrix.perl-version }}"
    needs: [ubuntu]
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
            - backend: JSON::XS
              backend-version: 4.00
              perl-version: 5.8
            - backend: JSON::XS
              backend-version: 3.02
              perl-version: 5.8
            - backend: JSON::XS
              backend-version: 2.34
              perl-version: 5.8
            - backend: JSON::PP
              backend-version: 2.97001
              perl-version: 5.8
            - backend: JSON::PP
              backend-version: 2.27400
              perl-version: 5.8
            - backend: JSON::PP
              backend-version: 2.27101
              perl-version: 5.8
            - backend: JSON::PP
              backend-version: 2.27101
              perl-version: 5.8
            - backend: Cpanel::JSON::XS
              backend-version: 4.08
              perl-version: 5.8
            - backend: Cpanel::JSON::XS
              backend-version: 3.0218
              perl-version: 5.8

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v1
      - name: perl -V
        run: perl -V
      - name: install backend
        run: cpanm -n ${{ matrix.backend }}@${{ matrix.backend-version }}
      - name: Makefile.PL
        run: perl -I$(pwd) Makefile.PL
      - name: make test
        run: PERL_JSON_BACKEND=${{ matrix.backend }} make test

  macOS:
    needs: [ubuntu]
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: macOS-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version: [latest]

    steps:
      - uses: actions/checkout@v1
      - name: perl -V
        run: perl -V
      - name: Makefile.PL
        run: perl -I$(pwd) Makefile.PL
      - name: make test
        run: make test

  # windows:
  #   needs: [ubuntu]
  #   env:
  #     PERL_USE_UNSAFE_INC: 0
  #     AUTHOR_TESTING: 0
  #     AUTOMATED_TESTING: 1
  #     RELEASE_TESTING: 0

  #   runs-on: windows-latest

  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       perl-version: [latest]

  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Set up Perl
  #       run: |
  #         choco install strawberryperl
  #         echo "##[add-path]C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin"
  #     - name: perl -V
  #       run: perl -V
  #     - name: Makefile.PL
  #       run: perl -I Makefile.PL
  #     - name: make test
  #       run: make test